[package]
name = "day19"
version = "0.1.0"
authors = ["Konrad <szymoniak.konrad@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
multimap = "0.8.0"
regex = "1.3.4"
